#!/usr/bin/env mash

Generate an exception, to check whether the reported file and line number are
correct.

Correct behavior: NameError, with traceback complaining about lines 21 and
29.


[[[ |||
  An irrelevant frame.
  [[[ |||
    Another irrelevant frame.
  ]]]
]]]



[[[
  def function_with_exception():
    a
]]]





[[[ 
  function_with_exception()
]]]

